<?php if(!defined('BASEPATH')) exit('No direct script access allowed'); ?>

<div class="relative-hidden ptb-15">
	<div class="flexcenter">
		<a name="fb_share" href="http://www.facebook.com/sharer.php?u=<?= "https://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]?>" onclick='window.open(this.href,"popupwindow","status=0,height=500,width=500,resizable=0,top=50,left=100");return false;' rel='noopener noreferrer' target='_blank' title='Facebook'><div class="facebook social-icon"><img src="<?= base_url("$this->theme_folder/$this->theme/images/iconsvg/social/facebook.svg") ?>"/></div></a>
		<a href="http://twitter.com/share?source=sharethiscom&text=<?= htmlspecialchars($single_artikel["judul"]);?>%0A&url=<?= "https://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI].'&via=rohman'?>" onclick='window.open(this.href,"popupwindow","status=0,height=500,width=500,resizable=0,top=50,left=100");return false;' rel='noopener noreferrer' target='_blank' title='Twitter'><div class="twitter social-icon"><img src="<?= base_url("$this->theme_folder/$this->theme/images/iconsvg/social/twitter.svg") ?>"/></div></a>
		<a href="mailto:?subject=<?= htmlspecialchars($single_artikel["judul"]);?>&body=<?= potong_teks($single_artikel["isi"], 1000);?> ... Selengkapnya di <?= "https://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]?>" title='Email'><div class="email social-icon"><img src="<?= base_url("$this->theme_folder/$this->theme/images/iconsvg/social/email.svg") ?>"/></div></a>
		<a href="https://telegram.me/share/url?url=<?= "https://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]?>&text=<?= htmlspecialchars($single_artikel["judul"]);?>%0A" onclick='window.open(this.href,"popupwindow","status=0,height=500,width=500,resizable=0,top=50,left=100");return false;' rel='noopener noreferrer' target='_blank' title='Telegram'><div class="telegram social-icon"><img src="<?= base_url("$this->theme_folder/$this->theme/images/iconsvg/social/telegram.svg") ?>"/></div></a>
		<a href="#" onclick="printDiv('printableArea')" title='Cetak Artikel'><div class="print social-icon"><img src="<?= base_url("$this->theme_folder/$this->theme/images/iconsvg/social/print.svg") ?>"/></div></a>
		<a href="https://api.whatsapp.com/send?text=<?= htmlspecialchars($single_artikel["judul"]);?>%0A<?= "https://".$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI]?>" onclick='window.open(this.href,"popupwindow","status=0,height=500,width=500,resizable=0,top=50,left=100");return false;' rel='noopener noreferrer' target='_blank' title='Whatsapp'><div class="whatsapp social-icon"><img src="<?= base_url("$this->theme_folder/$this->theme/images/iconsvg/social/whatsapp.svg") ?>"/></div></a>
	</div>
</div>	
